import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import HomePageNavbar from "@/components/HomePageNavbar";

const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorPrimary: "#e9b44c",
          colorBackground: "#fffef0",
          colorForeground: "#363636",
          colorPrimaryForeground: "#363636",
          colorInputForeground: "#363636",
          fontSize: "14px",
        },
      }}
    >
      <html lang="en" className={`${bricolage.variable} h-full antialiased`}>
        <body className="bg-background text-foreground">
          <HomePageNavbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
