import type { Metadata } from "next";
import { Bricolage_Grotesque, Geist } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorPrimary: "#e9b44c",
          colorBackground: "#fffef0",
          colorForeground: "#363636",
          colorPrimaryForeground: "#363636",
          colorInputForeground: "#363636",
          fontSize: "14px",
        },
      }}
    >
      <html lang="en" className={cn("h-full", "antialiased", bricolage.variable, "font-sans", geist.variable)}>
        <body className="bg-background text-foreground">{children}</body>
      </html>
    </ClerkProvider>
  );
}
